spring:
  application:
    name: Budget_Manager

# Server configuration
  datasource:
    url: jdbc:mysql://localhost:3306/TPO
    username: root
    password: dementor

  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update

    show-sql: true
    properties:
      hibernate:
        format_sql=true:

# Jwt configuration
  security:
    jwt:
      expiration: 600000